services:
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: ias
      POSTGRES_PASSWORD: ias
      POSTGRES_DB: skph
    container_name: skph
    ports:
      - "5432:5432"