/*-- Tworzenie tabeli Capability
CREATE TABLE capability (
                            capability_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            capability_name VARCHAR(255) UNIQUE NOT NULL
);

-- Tworzenie tabeli Role
CREATE TABLE role (
                      role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      role_name VARCHAR(255) UNIQUE NOT NULL
);

-- Tworzenie tabeli User
CREATE TABLE user (
                        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255) UNIQUE NOT NULL,
                        password_hash VARCHAR(255) NOT NULL,
                        role_id INTEGER NOT NULL,
                        first_name VARCHAR(255) NOT NULL,
                        last_name VARCHAR(255) NOT NULL,
                        last_login TIMESTAMP,
                        FOREIGN KEY (role_id) REFERENCES role(role_id) ON DELETE CASCADE
);

-- Tworzenie tabeli role_capability (łącząca tabela dla wielu do wielu)
CREATE TABLE role_capability (
                                 role_id INTEGER NOT NULL,
                                 capability_id INTEGER NOT NULL,
                                 PRIMARY KEY (role_id, capability_id),
                                 FOREIGN KEY (role_id) REFERENCES role(role_id) ON DELETE CASCADE,
                                 FOREIGN KEY (capability_id) REFERENCES capability(capability_id) ON DELETE CASCADE
);*/