###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "Powiadomienia",
  "password": "ZAQ!2wsx",
  "firstName": "Mateusz",
  "lastName": "Jakub",
  "roleName": "ROLE_WOLONTARIUSZ"
}

###
POST http://localhost:8080/announcements
Content-Type: application/json

{
    "message": "msg1",
    "title": "title",
    "type": "INFORMATION"
}

###
POST http://localhost:8080/announcements
Content-Type: application/json

{
  "message":"msg2",
  "title":"title",
  "type":"WARNING"
}

###
POST http://localhost:8080/announcements/2/hide
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/announcements/user/1

###
POST http://localhost:8080/notifications
Content-Type: application/json

{
  "message": "Masz nowe powiadomienie",
  "type": "INFORMATION",
  "userId": 1
}

###
GET http://localhost:8080/notifications/user/1

###
POST http://localhost:8080/notifications/1/hide

